sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jolapoin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jolapoin/react-test npm test -- --coverage

after_success:
  - docker build -t jolapoin/udemy-multi-client ./client
  - docker build -t jolapoin/udemy-multi-nginx ./nginx
  - docker build -t jolapoin/udemy-multi-server ./server
  - docker build -t jolapoin/udemy-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jolapoin/udemy-multi-client
  - docker push jolapoin/udemy-multi-nginx
  - docker push jolapoin/udemy-multi-server
  - docker push jolapoin/udemy-multi-worker
